// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wavialznxjylwuenybih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhdmlhbHpueGp5bHd1ZW55YmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTc5ODUsImV4cCI6MjA2NTgzMzk4NX0.DJ3S_J9E7MpG15F3iv-h-jUZ6ixdnbAhqhUBcglLuyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);